version: '3.1'

services:
  springboot:
    image: itssunnyy/spring-mongo:latest
    restart: always 
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=production
    - MONGO_DB_PASSWORD=production@123
    ports:
    - 8080:8080
    working_dir: /opt/app
    depends_on:
    - mongo
    networks:
    - springappnetwork

  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=production
    - MONGO_INITDB_ROOT_PASSWORD=production@123
    volumes:
    - mongodb:/data/db
    restart: always
    networks:
    - springappnetwork

volumes:
  mongodb:
    external: true

networks:
  springappnetwork:
    external: true